name: RiboNN
channels:
  - conda-forge
dependencies:
  - cuda-version=11.3
  - cudatoolkit=11.3.1
  - cudnn=8.9.7.29
  - lightning-utilities=0.10.1
  - mlflow=2.18.0
  - numpy=1.22.4
  - pandas=2.2.3
  - python=3.10.13
  - pytorch=1.13.1
  - pytorch-lightning=1.8.5
  - scikit-learn=1.0.2
  - torchmetrics=1.3.1
